---
- name: Configure VM provisioned by Terraform
  hosts: web
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a welcome page
      copy:
        dest: /var/www/html/index.html
        content: "Hello from Ansible!"
