all:
  children:
    new_vms:
      hosts:
        waveform-01:
          ansible_host: 192.168.1.129
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_python_interpreter: /usr/bin/python3
