---
- name: AD Integration Only
  hosts: new_vms
  become: yes
  vars:
    ad_domain: "haven.local"
    ad_join_user: "Administrator"

  tasks:
    - name: Install AD integration packages
      apt:
        name:
          - sssd-ad
          - sssd-tools
          - realmd
          - adcli
        state: present

    - name: Discover AD domain
      command: "realm -v discover {{ ad_domain }}"
      register: domain_discovery
      changed_when: false

    - name: Display domain join command
      debug:
        msg: |
          Please run the following command manually on each server:
          sudo realm -v join {{ ad_domain }} -U {{ ad_join_user }}

    - name: Wait for manual domain join
      pause:
        prompt: "Press ENTER after completing domain join on all servers"

    - name: Configure SSSD
      copy:
        content: |
          [sssd]
          domains = {{ ad_domain }}
          config_file_version = 2
          services = nss, pam

          [domain/{{ ad_domain }}]
          default_shell = /bin/bash
          krb5_store_password_if_offline = True
          cache_credentials = True
          krb5_realm = {{ ad_domain | upper }}
          realmd_tags = manages-system joined-with-adcli
          id_provider = ad
          fallback_homedir = /home/%u
          ad_domain = {{ ad_domain }}
          use_fully_qualified_names = False
          ldap_id_mapping = True
          access_provider = ad
        dest: /etc/sssd/sssd.conf
        mode: '0600'
        backup: yes
      notify: restart sssd

    - name: Enable automatic home directory creation
      command: pam-auth-update --enable mkhomedir

    - name: Configure sudoers for AD groups
      lineinfile:
        path: /etc/sudoers
        line: "%segunixadmin ALL=(ALL:ALL) ALL"
        validate: 'visudo -cf %s'
        backup: yes

    - name: Deny all realm access by default
      command: realm deny --all
      ignore_errors: yes

    - name: Permit segunixadmin group
      command: realm permit -g segunixadmin
      ignore_errors: yes

    - name: List realm configuration
      command: realm list
      register: realm_list
      changed_when: false

    - name: Display realm configuration
      debug:
        var: realm_list.stdout_lines

  handlers:
    - name: restart sssd
      systemd:
        name: sssd
        state: restarted
        enabled: yes